-- MySQL Script generated by MySQL Workbench
-- mar 22 oct 2019 20:59:26 CST
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

---

-- Schema mydb

---

---

-- Schema mydb

---

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

---

-- Table `mydb`.`Restautante`

---

CREATE TABLE IF NOT EXISTS `mydb`.`Restautante` (
`idRestautante` INT NOT NULL,
`Nombre_Restaurante` VARCHAR(45) NULL,
PRIMARY KEY (`idRestautante`))
ENGINE = InnoDB;

---

-- Table `mydb`.`Sucursal`

---

CREATE TABLE IF NOT EXISTS `mydb`.`Sucursal` (
`idSucursal` INT NOT NULL,
`Provincia` VARCHAR(45) NULL,
`Cantón` VARCHAR(45) NULL,
`Distrito` VARCHAR(45) NULL,
`Detalles` VARCHAR(45) NULL,
PRIMARY KEY (`idSucursal`))
ENGINE = InnoDB;

---

-- Table `mydb`.`Servicio`

---

CREATE TABLE IF NOT EXISTS `mydb`.`Servicio` (
`idServicio` INT NOT NULL,
`Descripcion` VARCHAR(150) NULL,
PRIMARY KEY (`idServicio`))
ENGINE = InnoDB;

---

-- Table `mydb`.`Reservacion`

---

CREATE TABLE IF NOT EXISTS `mydb`.`Reservacion` (
`idReservacion` INT NOT NULL,
`H_Inicio` TIME NOT NULL,
`H_Final.` TIME NULL,
`Fecha` DATE NULL,
PRIMARY KEY (`idReservacion`))
ENGINE = InnoDB;

---

-- Table `mydb`.`Cliente`

---

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
`SSID` INT NOT NULL,
`Nombre` VARCHAR(45) NULL,
`Apellido` VARCHAR(45) NULL,
`User` VARCHAR(45) NULL,
`Password` VARCHAR(45) NULL,
PRIMARY KEY (`SSID`))
ENGINE = InnoDB;

---

-- Table `mydb`.`ItemCompra`

---

CREATE TABLE IF NOT EXISTS `mydb`.`ItemCompra` (
`Cantidad` VARCHAR(45) NULL,
`Descripcion` VARCHAR(45) NULL,
`Metodo_pago` INT NOT NULL,
`Servicio_idServicio` INT NOT NULL,
PRIMARY KEY (`Servicio_idServicio`),
CONSTRAINT `fk_ItemCompra_Servicio`
FOREIGN KEY (`Servicio_idServicio`)
REFERENCES `mydb`.`Servicio` (`idServicio`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;

---

-- Table `mydb`.`Horario`

---

CREATE TABLE IF NOT EXISTS `mydb`.`Horario` (
`Dia` VARCHAR(15) NULL,
`H_Apertura` VARCHAR(45) NULL,
`H_Cierre` VARCHAR(45) NULL,
`Sucursal_idSucursal` INT NOT NULL,
PRIMARY KEY (`Sucursal_idSucursal`),
CONSTRAINT `fk_Horario_Sucursal1`
FOREIGN KEY (`Sucursal_idSucursal`)
REFERENCES `mydb`.`Sucursal` (`idSucursal`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;

---

-- Table `mydb`.`SucursalesXRestaurante`

---

CREATE TABLE IF NOT EXISTS `mydb`.`SucursalesXRestaurante` (
`Restautante_idRestautante` INT NOT NULL,
`Sucursal_idSucursal` INT NOT NULL,
PRIMARY KEY (`Restautante_idRestautante`, `Sucursal_idSucursal`),
INDEX `fk_SucursalesXRestaurante_Sucursal1_idx` (`Sucursal_idSucursal` ASC) VISIBLE,
CONSTRAINT `fk_SucursalesXRestaurante_Restautante1`
FOREIGN KEY (`Restautante_idRestautante`)
REFERENCES `mydb`.`Restautante` (`idRestautante`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_SucursalesXRestaurante_Sucursal1`
FOREIGN KEY (`Sucursal_idSucursal`)
REFERENCES `mydb`.`Sucursal` (`idSucursal`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;

---

-- Table `mydb`.`clientesXrestaurante`

---

CREATE TABLE IF NOT EXISTS `mydb`.`clientesXrestaurante` (
`Restautante_idRestautante` INT NOT NULL,
`Cliente_SSID` INT NOT NULL,
PRIMARY KEY (`Restautante_idRestautante`, `Cliente_SSID`),
INDEX `fk_clientesXrestaurante_Cliente1_idx` (`Cliente_SSID` ASC) VISIBLE,
CONSTRAINT `fk_clientesXrestaurante_Restautante1`
FOREIGN KEY (`Restautante_idRestautante`)
REFERENCES `mydb`.`Restautante` (`idRestautante`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_clientesXrestaurante_Cliente1`
FOREIGN KEY (`Cliente_SSID`)
REFERENCES `mydb`.`Cliente` (`SSID`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;

---

-- Table `mydb`.`Compra`

---

CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
`idCompra` INT NOT NULL,
PRIMARY KEY (`idCompra`))
ENGINE = InnoDB;

---

-- Table `mydb`.`itemsXcompra`

---

CREATE TABLE IF NOT EXISTS `mydb`.`itemsXcompra` (
`Compra_idCompra` INT NOT NULL,
`ItemCompra_Servicio_idServicio` INT NOT NULL,
PRIMARY KEY (`Compra_idCompra`, `ItemCompra_Servicio_idServicio`),
INDEX `fk_itemsXcompra_ItemCompra1_idx` (`ItemCompra_Servicio_idServicio` ASC) VISIBLE,
CONSTRAINT `fk_itemsXcompra_Compra1`
FOREIGN KEY (`Compra_idCompra`)
REFERENCES `mydb`.`Compra` (`idCompra`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_itemsXcompra_ItemCompra1`
FOREIGN KEY (`ItemCompra_Servicio_idServicio`)
REFERENCES `mydb`.`ItemCompra` (`Servicio_idServicio`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;

---

-- Table `mydb`.`comprasXcliente`

---

CREATE TABLE IF NOT EXISTS `mydb`.`comprasXcliente` (
`Compra_idCompra` INT NOT NULL,
`Cliente_SSID` INT NOT NULL,
PRIMARY KEY (`Compra_idCompra`, `Cliente_SSID`),
INDEX `fk_comprasXcliente_Cliente1_idx` (`Cliente_SSID` ASC) VISIBLE,
CONSTRAINT `fk_comprasXcliente_Compra1`
FOREIGN KEY (`Compra_idCompra`)
REFERENCES `mydb`.`Compra` (`idCompra`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_comprasXcliente_Cliente1`
FOREIGN KEY (`Cliente_SSID`)
REFERENCES `mydb`.`Cliente` (`SSID`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;

---

-- Table `mydb`.`serviciosXsucursal`

---

CREATE TABLE IF NOT EXISTS `mydb`.`serviciosXsucursal` (
`Servicio_idServicio` INT NOT NULL,
`Sucursal_idSucursal` INT NOT NULL,
PRIMARY KEY (`Servicio_idServicio`, `Sucursal_idSucursal`),
INDEX `fk_serviciosXsucursal_Sucursal1_idx` (`Sucursal_idSucursal` ASC) VISIBLE,
CONSTRAINT `fk_serviciosXsucursal_Servicio1`
FOREIGN KEY (`Servicio_idServicio`)
REFERENCES `mydb`.`Servicio` (`idServicio`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_serviciosXsucursal_Sucursal1`
FOREIGN KEY (`Sucursal_idSucursal`)
REFERENCES `mydb`.`Sucursal` (`idSucursal`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;

---

-- Table `mydb`.`reservacionesXservicioXsucursal`

---

CREATE TABLE IF NOT EXISTS `mydb`.`reservacionesXservicioXsucursal` (
`Reservacion_idReservacion` INT NOT NULL,
`Servicio_idServicio` INT NOT NULL,
`Sucursal_idSucursal` INT NOT NULL,
PRIMARY KEY (`Reservacion_idReservacion`, `Servicio_idServicio`, `Sucursal_idSucursal`),
INDEX `fk_reservacionesXservicioXsucursal_Servicio1_idx` (`Servicio_idServicio` ASC) VISIBLE,
INDEX `fk_reservacionesXservicioXsucursal_Sucursal1_idx` (`Sucursal_idSucursal` ASC) VISIBLE,
CONSTRAINT `fk_reservacionesXservicioXsucursal_Reservacion1`
FOREIGN KEY (`Reservacion_idReservacion`)
REFERENCES `mydb`.`Reservacion` (`idReservacion`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_reservacionesXservicioXsucursal_Servicio1`
FOREIGN KEY (`Servicio_idServicio`)
REFERENCES `mydb`.`Servicio` (`idServicio`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_reservacionesXservicioXsucursal_Sucursal1`
FOREIGN KEY (`Sucursal_idSucursal`)
REFERENCES `mydb`.`Sucursal` (`idSucursal`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;