-- MySQL Script generated by MySQL Workbench
-- vie 25 oct 2019 12:11:27 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test1` ;
USE `test1` ;

-- -----------------------------------------------------
-- Table `test1`.`Restautante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`Restaurante` (
  `idRestautante` INT NOT NULL,
  `Nombre_Restaurante` VARCHAR(45) NULL,
  PRIMARY KEY (`idRestautante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`Sucursal` (
  `idSucursal` INT NOT NULL,
  `Provincia` VARCHAR(45) NULL,
  `Cantón` VARCHAR(45) NULL,
  `Distrito` VARCHAR(45) NULL,
  `Detalles` VARCHAR(45) NULL,
  PRIMARY KEY (`idSucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`Servicio` (
  `idServicio` INT NOT NULL,
  `Descripcion` VARCHAR(150) NULL,
  PRIMARY KEY (`idServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`Reservacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`Reservacion` (
  `idReservacion` INT NOT NULL,
  `H_Inicio` TIME NOT NULL,
  `H_Final.` TIME NULL,
  `Fecha` DATE NULL,
  PRIMARY KEY (`idReservacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`Cliente` (
  `SSID` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `User` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`SSID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`ItemCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`ItemCompra` (
  `Cantidad` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Metodo_pago` INT NOT NULL,
  `Servicio_idServicio` INT NOT NULL,
  PRIMARY KEY (`Servicio_idServicio`),
  CONSTRAINT `fk_ItemCompra_Servicio`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `test1`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`Horario` (
  `Dia` VARCHAR(15) NULL,
  `H_Apertura` VARCHAR(45) NULL,
  `H_Cierre` VARCHAR(45) NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`Sucursal_idSucursal`),
  CONSTRAINT `fk_Horario_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `test1`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`SucursalesXRestaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`SucursalesXRestaurante` (
  `Restautante_idRestautante` INT NOT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`Restautante_idRestautante`, `Sucursal_idSucursal`),
  INDEX `fk_SucursalesXRestaurante_Sucursal1_idx` (`Sucursal_idSucursal` ASC),
  CONSTRAINT `fk_SucursalesXRestaurante_Restautante1`
    FOREIGN KEY (`Restautante_idRestautante`)
    REFERENCES `test1`.`Restautante` (`idRestautante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SucursalesXRestaurante_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `test1`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`clientesXrestaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`clientesXrestaurante` (
  `Restautante_idRestautante` INT NOT NULL,
  `Cliente_SSID` INT NOT NULL,
  PRIMARY KEY (`Restautante_idRestautante`, `Cliente_SSID`),
  INDEX `fk_clientesXrestaurante_Cliente1_idx` (`Cliente_SSID` ASC),
  CONSTRAINT `fk_clientesXrestaurante_Restautante1`
    FOREIGN KEY (`Restautante_idRestautante`)
    REFERENCES `test1`.`Restautante` (`idRestautante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientesXrestaurante_Cliente1`
    FOREIGN KEY (`Cliente_SSID`)
    REFERENCES `test1`.`Cliente` (`SSID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`Compra` (
  `idCompra` INT NOT NULL,
  PRIMARY KEY (`idCompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`itemsXcompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`itemsXcompra` (
  `Compra_idCompra` INT NOT NULL,
  `ItemCompra_Servicio_idServicio` INT NOT NULL,
  PRIMARY KEY (`Compra_idCompra`, `ItemCompra_Servicio_idServicio`),
  INDEX `fk_itemsXcompra_ItemCompra1_idx` (`ItemCompra_Servicio_idServicio` ASC),
  CONSTRAINT `fk_itemsXcompra_Compra1`
    FOREIGN KEY (`Compra_idCompra`)
    REFERENCES `test1`.`Compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemsXcompra_ItemCompra1`
    FOREIGN KEY (`ItemCompra_Servicio_idServicio`)
    REFERENCES `test1`.`ItemCompra` (`Servicio_idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`comprasXcliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`comprasXcliente` (
  `Compra_idCompra` INT NOT NULL,
  `Cliente_SSID` INT NOT NULL,
  PRIMARY KEY (`Compra_idCompra`, `Cliente_SSID`),
  INDEX `fk_comprasXcliente_Cliente1_idx` (`Cliente_SSID` ASC),
  CONSTRAINT `fk_comprasXcliente_Compra1`
    FOREIGN KEY (`Compra_idCompra`)
    REFERENCES `test1`.`Compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comprasXcliente_Cliente1`
    FOREIGN KEY (`Cliente_SSID`)
    REFERENCES `test1`.`Cliente` (`SSID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`serviciosXsucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`serviciosXsucursal` (
  `Servicio_idServicio` INT NOT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`Servicio_idServicio`, `Sucursal_idSucursal`),
  INDEX `fk_serviciosXsucursal_Sucursal1_idx` (`Sucursal_idSucursal` ASC),
  CONSTRAINT `fk_serviciosXsucursal_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `test1`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serviciosXsucursal_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `test1`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`reservacionesXservicioXsucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`reservacionesXservicioXsucursal` (
  `Reservacion_idReservacion` INT NOT NULL,
  `Servicio_idServicio` INT NOT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`Reservacion_idReservacion`, `Servicio_idServicio`, `Sucursal_idSucursal`),
  INDEX `fk_reservacionesXservicioXsucursal_Servicio1_idx` (`Servicio_idServicio` ASC),
  INDEX `fk_reservacionesXservicioXsucursal_Sucursal1_idx` (`Sucursal_idSucursal` ASC),
  CONSTRAINT `fk_reservacionesXservicioXsucursal_Reservacion1`
    FOREIGN KEY (`Reservacion_idReservacion`)
    REFERENCES `test1`.`Reservacion` (`idReservacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservacionesXservicioXsucursal_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `test1`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservacionesXservicioXsucursal_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `test1`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
